Use Crystal stdlib SNI implementation
Crystal 1.19.0 includes it, which cause a conflict:

    In src/stdlib/openssl_sni.cr:13:3

     13 | SSL_CTRL_SET_TLSEXT_SERVERNAME_CB  = 53
          ^--------------------------------
    Error: already initialized constant LibSSL::SSL_CTRL_SET_TLSEXT_SERVERNAME_CB

Replace custom openssl_sni.cr monkey-patch with the new
on_server_name callback added in crystal-lang/crystal#16452 by us

This has only been tested by existing specs.